### ISSUE TITLE
Only works when children are html nodes

### ISSUE THREAD

**Issue by StevenVerbiest** [rebassjs/space#2]
If the child of the `<Space>` component is another component instead of html, the spacing is not applied.

Demo: https://codesandbox.io/s/vv3vq2wkk5

**Comment by jxnblk** [comment]
The child components need to accept the `className` prop, which is a limitation with how CSS-in-JS works

**Comment by StevenVerbiest** [comment]
Alright, thanks for the info. I updated the example with an implemented solution.
