### ISSUE TITLE
Will override children

### ISSUE THREAD

**Issue by kristojorg** [rebassjs/space#3]
Hi there, after on convo on twitter I tried to get this to work where the parents sets default spacing, and children can override it. I wasn't able to increase the specificity of the children in `StyledChildren`, because in my case the children were `styled components`, and didn't have a `className` prop yet because they had not rendered. Wondering if you have any suggestions how to solve this?

[Here is a codesandbox](https://codesandbox.io/embed/k0r1549x63)

Happy to make a PR if you have any suggestions. I do prefer this approach to my former css-based approach, but so far it has the same precedence issue. 

Thanks again!

**Comment by jxnblk** [comment]
Sorry for the delay on this. I'm archiving this repo in favor of a monorepo here: https://github.com/rebassjs/rebass, but I think you can force a higher specificity in your example like this – though I'd be cautious about using this approach because it escalates specificity on the Box

```
const Box = styled.div`
  && {
    ${space}
    ${color}
  }
`;
```
