### ISSUE TITLE
Wondering about performance of this solution

### ISSUE THREAD

**Issue by sns2009** [rebassjs/space#4]
I consider two options for spacing:
1. Box component
2. Space component

In case of this code snippet(`n` items): 
```
items.map((text) => (
<Space/Box>
  <CustomComponent>
    {text}
  </CustomComponent>
</Space/Box>
))
```
What solution would be more performan in case of large `n`. 
Box component will create `n` extra divs.
Space component will clone the element `n` times.
Any thought on this?

**Comment by jxnblk** [comment]
I have no idea, but I'd imagine it's not something you need to worry too much about unless you're doing some huge data grid type stuff with windowing. That said, you should probably look into RUM or the react profiler if you're noticing issues
